#!/bin/bash

#make sure that the directory exists.
if [[ -d "$1" ]]; then
	./print_all_passengers_aux $1 | sort -s -k3 -n | while read -a line; do
		echo ${line[0]} ${line[1]}:${line[2]}:${line[3]}:${line[4]}
	done
fi